# How to use
- เปิด Playground mode ด้วยการกด `File` -> `Open in playground mode`
- พิมพ์เลขปีงบประมาณของงบที่ต้องการสร้าง csv ในช่อง `เลขปีงบประมาณ`
- copy url ของ Google Sheet ข้อมูลงบที่ validate แล้วมาใส่ในช่อง `url ของ Google Sheet Tree งบประมาณที่ validate แล้ว`
- copy url ของ Google Sheet ที่ต้องการสร้างตารางผลลัพธ์มาใส่ในช่อง `url ของ Google Sheet ที่ต้องการบันทึกผลลัพธ์`
- กด Run all
---
Note
- ในการรันครั้งแรกระบบจะขอให้ login ด้วย Google Account
- Login ด้วย account ที่มี permission แก้ไข [sheet สำหรับ validate](https://docs.google.com/spreadsheets/d/1zArSJZE1l3nuOMbPvnxNGmATLy1g1e0IjBcJkxJLFxU/edit?gid=51205943#gid=51205943?target=_blank)

In [1]:
#@title เลขปีงบประมาณ
BUDGET_YEAR = None #@param {type:"integer"}

In [2]:
#@title url ของ Google Sheet Tree งบประมาณที่ validate แล้ว
TREE_SHEET_URL = '' # @param {"type": "string"}

In [3]:
#@title url ของ Google Sheet ที่ต้องการบันทึกผลลัพธ์
OUTPUT_SHEET_URL = '' # @param {"type": "string"}

# Code

In [4]:
import os
import re
import requests
import json
import pandas as pd
import datetime

## Authenticate to Google

In [5]:
# Connect to Google Account & Google Sheet
from google.colab import auth
import gspread
from google.auth import default

auth.authenticate_user()
creds, _ = default()
gc = gspread.authorize(creds)

## Connect to Google Sheet

In [6]:
gc = gspread.authorize(creds)

In [7]:
# Get validation tree sheet
validate_sheet = gc.open_by_url(TREE_SHEET_URL)
validate_sheet

In [8]:
# Get output sheet
output_sheet = gc.open_by_url(OUTPUT_SHEET_URL)
output_sheet

## Clone & Install Validation Tool

In [9]:
!rm -rf wevis-openbudget-validation-tools && git clone https://github.com/wevisdemo/wevis-openbudget-validation-tools.git

Cloning into 'wevis-openbudget-validation-tools'...
remote: Enumerating objects: 459, done.
remote: Counting objects: 100% (459/459), done.
remote: Compressing objects: 100% (273/273), done.
remote: Total 459 (delta 227), reused 405 (delta 173), pack-reused 0 (from 0)
Receiving objects: 100% (459/459), 88.29 KiB | 2.52 MiB/s, done.
Resolving deltas: 100% (227/227), done.

In [10]:
!pip install -e "wevis-openbudget-validation-tools/open-budget-tree-validator" -q

  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
  Building editable for open_budget_tree_validator (pyproject.toml) ... done

In [11]:
import site

for sitepackages in site.getsitepackages():
    site.addsitedir(sitepackages)

# Build Final CSV

## Load ministry names

In [12]:
ministry_name_df = pd.read_csv("https://raw.githubusercontent.com/wevisdemo/wevis-openbudget-ocr/refs/heads/master/data/min_agc_names.csv")
ministry_name_df.head(5)

            min_name                             agc_name
0  สำนักนายกรัฐมนตรี        สำนักงานปลัดสำนักนายกรัฐมนตรี
1  สำนักนายกรัฐมนตรี                     กรมประชาสัมพันธ์
2  สำนักนายกรัฐมนตรี  สำนักงานคณะกรรมการคุ้มครองผู้บริโภค
3  สำนักนายกรัฐมนตรี           สำนักเลขาธิการนายกรัฐมนตรี
4  สำนักนายกรัฐมนตรี            สำนักเลขาธิการคณะรัฐมนตรี

In [13]:
ministries_name = ministry_name_df['min_name'].unique()
ministries_name

array(['สำนักนายกรัฐมนตรี', 'กระทรวงกลาโหม', 'กระทรวงการคลัง',
       'กระทรวงการต่างประเทศ', 'กระทรวงการท่องเที่ยวและกีฬา',
       'กระทรวงการพัฒนาสังคมและความมั่นคงของมนุษย์',
       'กระทรวงเกษตรและสหกรณ์', 'กระทรวงคมนาคม',
       'กระทรวงทรัพยากรธรรมชาติและสิ่งแวดล้อม',
       'กระทรวงดิจิทัลเพื่อเศรษฐกิจและสังคม', 'กระทรวงพลังงาน',
       'กระทรวงพาณิชย์', 'กระทรวงมหาดไทย', 'กระทรวงยุติธรรม',
       'กระทรวงแรงงาน', 'กระทรวงวัฒนธรรม', 'กระทรวงศึกษาธิการ',
       'กระทรวงสาธารณสุข', 'กระทรวงอุตสาหกรรม',
       'กระทรวงการอุดมศึกษา วิทยาศาสตร์ วิจัยและนวัตกรรม',
       'ส่วนราชการไม่สังกัดสำนักนายกรัฐมนตรี กระทรวง หรือทบวง และหน่วยงานภายใต้การควบคุมดูแลของนายกรัฐมนตรี',
       'หน่วยงานของรัฐสภา', 'หน่วยงานของศาล',
       'หน่วยงานขององค์กรอิสระและองค์กรอัยการ', 'รัฐวิสาหกิจ',
       'ส่วนราชการในพระองค์', 'สภากาชาดไทย', 'หน่วยงานอื่นของรัฐ',
       'จังหวัดและกลุ่มจังหวัด', 'องค์กรปกครองส่วนท้องถิ่น',
       'ทุนหมุนเวียน', 'กองทุนและเงินทุนหมุนเวียน', 'งบกลาง',
       'รายจ่ายเพื่อชดใช้เงินคงคลัง'], dtype=object)

# Build DF for each Ministry

In [14]:
from open_budget_tree_validator import BudgetTree

In [17]:
added_ministries = set()

final_df = None
for sheet in validate_sheet.worksheets():
  sheet_title = sheet.title

  matched_ministry_name = re.search(
      r"(" + "|".join(ministries_name) + ")",
      sheet_title
  )
  if matched_ministry_name and not re.search(r"\[", sheet_title):
    if matched_ministry_name.group(1) not in added_ministries:

      print(f"process {sheet_title} ...")

      sheet_values = sheet.get_all_values()
      df = pd.DataFrame(sheet_values[1:], columns=sheet_values[0])
      budget_tree = BudgetTree(budget_tree_df=df, budget_year=BUDGET_YEAR)
      added_ministries.add(matched_ministry_name.group(1))

      if final_df is None:
        final_df = budget_tree.build_final_df(BUDGET_YEAR)
        continue

      final_df = pd.concat([
          final_df,
          budget_tree.build_final_df(BUDGET_YEAR)
      ])

process กระทรวงการอุดมศึกษา วิทยาศาสตร์ วิจัยและนวัตกรรม ...

/content/wevis-openbudget-validation-tools/open-budget-tree-validator/src/open_budget_tree_validator/budget_tree.py:150: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  final_df.loc[:, 'FISCAL_YEAR'] = final_df['FISCAL_YEAR'].fillna(budget_year).astype(int)

process กระทรวงการท่องเที่ยวและกีฬา ...

/content/wevis-openbudget-validation-tools/open-budget-tree-validator/src/open_budget_tree_validator/budget_tree.py:150: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  final_df.loc[:, 'FISCAL_YEAR'] = final_df['FISCAL_YEAR'].fillna(budget_year).astype(int)

process กระทรวงมหาดไทย ...

/content/wevis-openbudget-validation-tools/open-budget-tree-validator/src/open_budget_tree_validator/budget_tree.py:150: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  final_df.loc[:, 'FISCAL_YEAR'] = final_df['FISCAL_YEAR'].fillna(budget_year).astype(int)

process กระทรวงดิจิทัลเพื่อเศรษฐกิจและสังคม ...

/content/wevis-openbudget-validation-tools/open-budget-tree-validator/src/open_budget_tree_validator/budget_tree.py:150: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  final_df.loc[:, 'FISCAL_YEAR'] = final_df['FISCAL_YEAR'].fillna(budget_year).astype(int)

process กระทรวงพลังงาน ...

/content/wevis-openbudget-validation-tools/open-budget-tree-validator/src/open_budget_tree_validator/budget_tree.py:150: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  final_df.loc[:, 'FISCAL_YEAR'] = final_df['FISCAL_YEAR'].fillna(budget_year).astype(int)

process กระทรวงศึกษาธิการ ...

/content/wevis-openbudget-validation-tools/open-budget-tree-validator/src/open_budget_tree_validator/budget_tree.py:150: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  final_df.loc[:, 'FISCAL_YEAR'] = final_df['FISCAL_YEAR'].fillna(budget_year).astype(int)

process กระทรวงวัฒนธรรม ...

/content/wevis-openbudget-validation-tools/open-budget-tree-validator/src/open_budget_tree_validator/budget_tree.py:150: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  final_df.loc[:, 'FISCAL_YEAR'] = final_df['FISCAL_YEAR'].fillna(budget_year).astype(int)

process งบกลาง ...

/content/wevis-openbudget-validation-tools/open-budget-tree-validator/src/open_budget_tree_validator/budget_tree.py:150: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  final_df.loc[:, 'FISCAL_YEAR'] = final_df['FISCAL_YEAR'].fillna(budget_year).astype(int)

process กระทรวงการคลัง ...

/content/wevis-openbudget-validation-tools/open-budget-tree-validator/src/open_budget_tree_validator/budget_tree.py:150: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  final_df.loc[:, 'FISCAL_YEAR'] = final_df['FISCAL_YEAR'].fillna(budget_year).astype(int)

process กระทรวงการพัฒนาสังคมและความมั่นคงของมนุษย์ ...

/content/wevis-openbudget-validation-tools/open-budget-tree-validator/src/open_budget_tree_validator/budget_tree.py:150: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  final_df.loc[:, 'FISCAL_YEAR'] = final_df['FISCAL_YEAR'].fillna(budget_year).astype(int)

process กระทรวงพาณิชย์ ...

/content/wevis-openbudget-validation-tools/open-budget-tree-validator/src/open_budget_tree_validator/budget_tree.py:150: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  final_df.loc[:, 'FISCAL_YEAR'] = final_df['FISCAL_YEAR'].fillna(budget_year).astype(int)

process กระทรวงแรงงาน ...

/content/wevis-openbudget-validation-tools/open-budget-tree-validator/src/open_budget_tree_validator/budget_tree.py:150: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  final_df.loc[:, 'FISCAL_YEAR'] = final_df['FISCAL_YEAR'].fillna(budget_year).astype(int)

process กระทรวงอุตสาหกรรม ...

/content/wevis-openbudget-validation-tools/open-budget-tree-validator/src/open_budget_tree_validator/budget_tree.py:150: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  final_df.loc[:, 'FISCAL_YEAR'] = final_df['FISCAL_YEAR'].fillna(budget_year).astype(int)

process กระทรวงการต่างประเทศ ...

/content/wevis-openbudget-validation-tools/open-budget-tree-validator/src/open_budget_tree_validator/budget_tree.py:150: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  final_df.loc[:, 'FISCAL_YEAR'] = final_df['FISCAL_YEAR'].fillna(budget_year).astype(int)

process กระทรวงทรัพยากรธรรมชาติและสิ่งแวดล้อม ...

/content/wevis-openbudget-validation-tools/open-budget-tree-validator/src/open_budget_tree_validator/budget_tree.py:150: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  final_df.loc[:, 'FISCAL_YEAR'] = final_df['FISCAL_YEAR'].fillna(budget_year).astype(int)

process กระทรวงยุติธรรม ...

/content/wevis-openbudget-validation-tools/open-budget-tree-validator/src/open_budget_tree_validator/budget_tree.py:150: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  final_df.loc[:, 'FISCAL_YEAR'] = final_df['FISCAL_YEAR'].fillna(budget_year).astype(int)

process จังหวัดและกลุ่มจังหวัด ...

/content/wevis-openbudget-validation-tools/open-budget-tree-validator/src/open_budget_tree_validator/budget_tree.py:150: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  final_df.loc[:, 'FISCAL_YEAR'] = final_df['FISCAL_YEAR'].fillna(budget_year).astype(int)

process กระทรวงเกษตรและสหกรณ์ ...

/content/wevis-openbudget-validation-tools/open-budget-tree-validator/src/open_budget_tree_validator/budget_tree.py:150: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  final_df.loc[:, 'FISCAL_YEAR'] = final_df['FISCAL_YEAR'].fillna(budget_year).astype(int)

process กระทรวงคมนาคม ...

/content/wevis-openbudget-validation-tools/open-budget-tree-validator/src/open_budget_tree_validator/budget_tree.py:150: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  final_df.loc[:, 'FISCAL_YEAR'] = final_df['FISCAL_YEAR'].fillna(budget_year).astype(int)

process กระทรวงสาธารณสุข ...

/content/wevis-openbudget-validation-tools/open-budget-tree-validator/src/open_budget_tree_validator/budget_tree.py:150: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  final_df.loc[:, 'FISCAL_YEAR'] = final_df['FISCAL_YEAR'].fillna(budget_year).astype(int)

process หน่วยงานอื่นของรัฐ ...

/content/wevis-openbudget-validation-tools/open-budget-tree-validator/src/open_budget_tree_validator/budget_tree.py:150: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  final_df.loc[:, 'FISCAL_YEAR'] = final_df['FISCAL_YEAR'].fillna(budget_year).astype(int)
/content/wevis-openbudget-validation-tools/open-budget-tree-validator/src/open_budget_tree_validator/budget_tree.py:150: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  final_df.loc[:, 'FISCAL_YEAR'] = final_df['FISCAL_YEAR'].fillna(budget_year).astype(int)

process ส่วนราชการในพระองค์ ...
process ส่วนราชการไม่สังกัดสำนักนายกรัฐมนตรี กระทรวง หรือทบวง และหน่วยงานภายใต้การควบคุมดูแลของนายกรัฐมนตรี ...

/content/wevis-openbudget-validation-tools/open-budget-tree-validator/src/open_budget_tree_validator/budget_tree.py:150: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  final_df.loc[:, 'FISCAL_YEAR'] = final_df['FISCAL_YEAR'].fillna(budget_year).astype(int)

process รัฐวิสาหกิจ ...

/content/wevis-openbudget-validation-tools/open-budget-tree-validator/src/open_budget_tree_validator/budget_tree.py:150: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  final_df.loc[:, 'FISCAL_YEAR'] = final_df['FISCAL_YEAR'].fillna(budget_year).astype(int)

process สำนักนายกรัฐมนตรี ...

/content/wevis-openbudget-validation-tools/open-budget-tree-validator/src/open_budget_tree_validator/budget_tree.py:150: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  final_df.loc[:, 'FISCAL_YEAR'] = final_df['FISCAL_YEAR'].fillna(budget_year).astype(int)

process สภากาชาดไทย ...

/content/wevis-openbudget-validation-tools/open-budget-tree-validator/src/open_budget_tree_validator/budget_tree.py:150: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  final_df.loc[:, 'FISCAL_YEAR'] = final_df['FISCAL_YEAR'].fillna(budget_year).astype(int)

process รายจ่ายเพื่อชดใช้เงินคงคลัง ...

/content/wevis-openbudget-validation-tools/open-budget-tree-validator/src/open_budget_tree_validator/budget_tree.py:150: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  final_df.loc[:, 'FISCAL_YEAR'] = final_df['FISCAL_YEAR'].fillna(budget_year).astype(int)

process ทุนหมุนเวียน ...

/content/wevis-openbudget-validation-tools/open-budget-tree-validator/src/open_budget_tree_validator/budget_tree.py:150: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  final_df.loc[:, 'FISCAL_YEAR'] = final_df['FISCAL_YEAR'].fillna(budget_year).astype(int)

process หน่วยงานของรัฐสภา ...

/content/wevis-openbudget-validation-tools/open-budget-tree-validator/src/open_budget_tree_validator/budget_tree.py:150: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  final_df.loc[:, 'FISCAL_YEAR'] = final_df['FISCAL_YEAR'].fillna(budget_year).astype(int)

process หน่วยงานของศาล ...

/content/wevis-openbudget-validation-tools/open-budget-tree-validator/src/open_budget_tree_validator/budget_tree.py:150: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  final_df.loc[:, 'FISCAL_YEAR'] = final_df['FISCAL_YEAR'].fillna(budget_year).astype(int)

process หน่วยงานขององค์กรอิสระและองค์กรอัยการ ...

/content/wevis-openbudget-validation-tools/open-budget-tree-validator/src/open_budget_tree_validator/budget_tree.py:150: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  final_df.loc[:, 'FISCAL_YEAR'] = final_df['FISCAL_YEAR'].fillna(budget_year).astype(int)

process องค์กรปกครองส่วนท้องถิ่น ...

/content/wevis-openbudget-validation-tools/open-budget-tree-validator/src/open_budget_tree_validator/budget_tree.py:150: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  final_df.loc[:, 'FISCAL_YEAR'] = final_df['FISCAL_YEAR'].fillna(budget_year).astype(int)

process กระทรวงกลาโหม ...

/content/wevis-openbudget-validation-tools/open-budget-tree-validator/src/open_budget_tree_validator/budget_tree.py:150: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  final_df.loc[:, 'FISCAL_YEAR'] = final_df['FISCAL_YEAR'].fillna(budget_year).astype(int)

In [18]:
final_df.head(5)

,REF_DOC,REF_PAGE_NO,MINISTRY,BUDGETARY_UNIT,BUDGET_PLAN,CROSS_FUNC?,OUTPUT,PROJECT,CATEGORY_LV1,CATEGORY_LV2,CATEGORY_LV3,CATEGORY_LV4,CATEGORY_LV5,CATEGORY_LV6,CATEGORY_LV7,ITEM_DESCRIPTION,AMOUNT,FISCAL_YEAR,OBLIGED?
0,1790738926_6118.pdf,63,กระทรวงการอุดมศึกษา วิทยาศาสตร์ วิจัยและนวัตกรรม,สำนักงานปลัดกระทรวงการอุดมศึกษา วิทยาศาสตร์ วิ...,แผนงานบุคลากรภาครัฐ,False,,,งบบุคลากร,เงินเดือนและค่าจ้างประจำ,,,,,,เงินเดือน,273522700.0,2027,False
1,1790738926_6118.pdf,63,กระทรวงการอุดมศึกษา วิทยาศาสตร์ วิจัยและนวัตกรรม,สำนักงานปลัดกระทรวงการอุดมศึกษา วิทยาศาสตร์ วิ...,แผนงานบุคลากรภาครัฐ,False,,,งบบุคลากร,เงินเดือนและค่าจ้างประจำ,,,,,,ค่าจ้างประจํา,11881800.0,2027,False
2,1790738926_6118.pdf,63,กระทรวงการอุดมศึกษา วิทยาศาสตร์ วิจัยและนวัตกรรม,สำนักงานปลัดกระทรวงการอุดมศึกษา วิทยาศาสตร์ วิ...,แผนงานบุคลากรภาครัฐ,False,,,งบบุคลากร,,,,,,,ค่าจ้างชั่วคราว,3744100.0,2027,False
3,1790738926_6118.pdf,63,กระทรวงการอุดมศึกษา วิทยาศาสตร์ วิจัยและนวัตกรรม,สำนักงานปลัดกระทรวงการอุดมศึกษา วิทยาศาสตร์ วิ...,แผนงานบุคลากรภาครัฐ,False,,,งบบุคลากร,,,,,,,ค่าตอบแทนพนักงานราชการ,15502700.0,2027,False
4,1790738926_6118.pdf,63,กระทรวงการอุดมศึกษา วิทยาศาสตร์ วิจัยและนวัตกรรม,สำนักงานปลัดกระทรวงการอุดมศึกษา วิทยาศาสตร์ วิ...,แผนงานบุคลากรภาครัฐ,False,,,งบดำเนินงาน,ค่าตอบแทน ใช้สอยและวัสดุ,,,,,,ค่าเช่าบ้าน,5776900.0,2027,False

# Add new Sheet

In [19]:
import zoneinfo

bangkok_tz = zoneinfo.ZoneInfo("Asia/Bangkok")
now_bangkok = datetime.datetime.now(bangkok_tz)

sheet_title = now_bangkok.date().isoformat() + '#'
sheet_title += now_bangkok.strftime("%H:%M:%S")

new_sheet = output_sheet.add_worksheet(
    title=sheet_title,
    rows=len(final_df.index),
    cols=len(final_df.columns)
)
new_sheet.update(
    [final_df.columns.values.tolist()] + final_df.values.tolist(),
    value_input_option='USER_ENTERED'
)

{'spreadsheetId': '1tr4SZDs0Si4OFePFF5ZiaEwbDhaV4XgG5m6lE8FBjig',
 'updatedRange': "'2026-10-28#16:00:03'!A1:S66868",
 'updatedRows': 66868,
 'updatedColumns': 19,
 'updatedCells': 1270237}